-- 1.管理员表
DROP TABLE admin;
CREATE TABLE admin(
id NUMBER PRIMARY KEY,
username VARCHAR2(255) NOT NULL,
pAssword VARCHAR2(255) NOT NULL); 

COMMENT ON COLUMN admin.username IS '用户名';
COMMENT ON COLUMN admin.pAssword IS '密码';

-- 用序列与触发器设置主键id自增，下同
CREATE SEQUENCE admin_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER admin_INS_TRG BEFORE INSERT ON admin FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT admin_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 2.图书表
-- DROP TABLE book;
CREATE TABLE book(
id NUMBER PRIMARY KEY,
name VARCHAR2(255) NOT NULL,
author1 VARCHAR2(255) NOT NULL,
author2 VARCHAR(255),
author3 VARCHAR(255),
isbn VARCHAR2(255) NOT NULL,
publish VARCHAR2(255),
publishDate DATE,
price NUMBER NOT NULL,
img VARCHAR2(255),
summary VARCHAR2(1024),
type NUMBER);

COMMENT ON COLUMN book.name IS '书名';
COMMENT ON COLUMN book.author1 IS '作者1';
COMMENT ON COLUMN book.author2 IS '作者2';
COMMENT ON COLUMN book.author3 IS '作者3';
COMMENT ON COLUMN book.isbn IS 'isbn标识码';
COMMENT ON COLUMN book.publish IS '出版社';
COMMENT ON COLUMN book.publishDate IS '出版日期';
COMMENT ON COLUMN book.price IS '价格';
COMMENT ON COLUMN book.img IS '封面图片url';
COMMENT ON COLUMN book.summary IS '摘要';
COMMENT ON COLUMN book.type IS '图书类型id，见book_type表';

CREATE SEQUENCE book_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER book_INS_TRG BEFORE INSERT ON book FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT book_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 3.图书类型表
-- DROP TABLE book_type;
CREATE TABLE book_type(
id NUMBER PRIMARY KEY,
name VARCHAR2(255) NOT NULL);

COMMENT ON COLUMN book_type.name IS '图书类型名';

CREATE SEQUENCE book_type_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER book_type_INS_TRG BEFORE INSERT ON book_type FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT book_type_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 4.读者表
-- DROP TABLE reader;
CREATE TABLE reader(
id NUMBER PRIMARY KEY,
name VARCHAR2(255) NOT NULL,
telephone VARCHAR2(255) NOT NULL,
email VARCHAR2(255),
type NUMBER);

COMMENT ON COLUMN reader.name IS '姓名';
COMMENT ON COLUMN reader.telephone IS '联系电话';
COMMENT ON COLUMN reader.email IS '邮箱';
COMMENT ON COLUMN reader.type IS '读者类型id，见reader_type表';

CREATE SEQUENCE reader_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER reader_INS_TRG BEFORE INSERT ON reader FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT reader_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 5.读者类型表
-- DROP TABLE reader_type;
CREATE TABLE reader_type(
id NUMBER PRIMARY KEY,
name VARCHAR2(255) NOT NULL);

COMMENT ON COLUMN reader_type.name IS '读者类型名';

CREATE SEQUENCE reader_type_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER reader_type_INS_TRG BEFORE INSERT ON reader_type FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT reader_type_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 6.借阅表
-- DROP TABLE borrow;
CREATE TABLE borrow(    
id NUMBER PRIMARY KEY,
reader_id NUMBER NOT NULL,
book_id NUMBER NOT NULL,
borrow_date DATE,
due_date DATE,
act_due_date DATE);

COMMENT ON COLUMN borrow.borrow_date IS '借阅日期';
COMMENT ON COLUMN borrow.due_date IS '应还日期';
COMMENT ON COLUMN borrow.act_due_date IS '实际归还日期';

CREATE SEQUENCE borrow_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER borrow_INS_TRG BEFORE INSERT ON borrow FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT borrow_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 7.预约表
-- DROP TABLE preconcert;
CREATE TABLE preconcert(    
id NUMBER PRIMARY KEY,
reader_id NUMBER NOT NULL,
book_id NUMBER NOT NULL,
pre_date DATE NOT NULL);

COMMENT ON COLUMN preconcert.pre_date IS '预约日期';

CREATE SEQUENCE preconcert_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER preconcert_INS_TRG BEFORE INSERT ON preconcert FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT preconcert_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- 8.规则表
-- DROP TABLE rule;
CREATE TABLE rule(
id NUMBER PRIMARY KEY,
reader_type NUMBER NOT NULL,
book_type NUMBER NOT NULL,
days NUMBER NOT NULL,
num NUMBER NOT NULL,
renew NUMBER NOT NULL);

COMMENT ON COLUMN rule.days IS '还书期限';
COMMENT ON COLUMN rule.num IS '可借书籍本数';
COMMENT ON COLUMN rule.renew IS '续借次数';

CREATE SEQUENCE rule_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER rule_INS_TRG BEFORE INSERT ON rule FOR EACH ROW WHEN(NEW.ID IS NULL)
BEGIN
SELECT rule_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;